
<link href="<?php echo $this->baseUrl($this->cssHelper) ;?>"
	media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript"
	src="<?php echo $this->baseUrl($this->jsHelper)?>"></script>
	
	
<div class="modal-dialog modal-md">
	<div class="modal-content">
		<form action="javascript:;" id="frmPesquisar" data-url="<?php echo $this->baseUrl();?>/default/usuariogrupo/listar/type/json" class="form">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">X</span>
					<span class="sr-only">Fechar</span>
				</button>
				<h4 class="modal-title">Filtrar Resultados</h4>
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Id</label>
				<input type="text" name="id" id="idPesquisar" class="form-control">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Nome</label>
				<input type="text" name="role" id="nomePesquisar" class="form-control">
			</div>
			<div class="modal-footer" style="margin-top: 5px;">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<button type="button" class="btn btn-primary botaoPesquisar">Pesquisar</button>
			</div>
		</form>
	</div> <!-- /.modal-content -->
</div> <!-- /.modal-dialog -->
