<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="UTF-8" />
    <title>PAINEL ADMINISTRATIVO</title>
     <meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
     <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <!-- GLOBAL STYLES -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('plugins/bootstrap/css/bootstrap.css');?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/main.css');?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/theme.css');?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/MoneAdmin.css');?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('plugins/Font-Awesome/css/font-awesome.css');?>" />
    <!--END GLOBAL STYLES -->

    <!-- PAGE LEVEL STYLES -->
    <link href="<?php echo $this->baseUrl('css/layout2.css');?>" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl('plugins/flot/examples/examples.css');?>" rel="stylesheet" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('plugins/timeline/timeline.css');?>" />
    <!-- END PAGE LEVEL  STYLES -->
     <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>

    <!-- END HEAD -->

    <!-- BEGIN BODY -->
<body class="padTop53 " >

    <!-- MAIN WRAPPER -->
    <div id="wrap" >
        

        <!-- HEADER SECTION -->
        <div id="top">

            <nav class="navbar navbar-inverse navbar-fixed-top " style="padding-top: 10px;">
                <a data-original-title="Show/Hide Menu" data-placement="bottom" data-tooltip="tooltip" class="accordion-toggle btn btn-primary btn-sm visible-xs" data-toggle="collapse" href="#menu" id="menu-toggle">
                    <i class="icon-align-justify"></i>
                </a>
                <!-- LOGO SECTION -->
                <header class="navbar-header">

                    <a href="index.html" class="navbar-brand">
                    <img src="http://netsuprema.com.br/media/imagem/topo/logo.png" alt="" width="120" />
                        
                        </a>
                </header>
                <!-- END LOGO SECTION -->
                <ul class="nav navbar-top-links navbar-right">

                    <!-- MESSAGES SECTION -->
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <span class="label label-success">2</span>    <i class="icon-envelope-alt"></i>&nbsp; <i class="icon-chevron-down"></i>
                        </a>

                        <ul class="dropdown-menu dropdown-messages">
                            <?php for($i=0;$i<3;$i++):?>
                            <li>
                                <a href="#">
                                    <div>
                                        <strong>João Clebim</strong>
                                        <span class="pull-right text-muted">
                                            <em>Sábado 19/02</em>
                                        </span>
                                    </div>
                                    <div>Você vendeu muito imóvel hoje?
                                         <br />
                                        <span class="label label-success"> ROOT </span> 
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <?php endfor;?>
                            <li>
                                <a class="text-center" href="#">
                                    <strong>Veja Mais</strong>
                                    <i class="icon-angle-right"></i>
                                </a>
                            </li>
                        </ul>

                    </li>
                    <!--END MESSAGES SECTION -->

                    <!--ALERTS SECTION -->
                    <li class="chat-panel dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <span class="label label-info">8</span>   <i class="icon-comments"></i>&nbsp; <i class="icon-chevron-down"></i>
                        </a>

                        <ul class="dropdown-menu dropdown-alerts">
                            <?php for($i=0;$i<10;$i++):?>
                            <li>
                                <a href="#">
                                    <div>
                                        <i class="icon-comment" ></i> New Comment
                                    <span class="pull-right text-muted small"> 4 minutes ago</span>
                                    </div>
                                </a>
                            </li>
                            <li class="divider"></li>
                            <?php endfor;?>
                        </ul>

                    </li>
                    <!-- END ALERTS SECTION -->

                    <!--ADMIN SETTINGS SECTIONS -->

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="icon-user "></i>&nbsp; <i class="icon-chevron-down "></i>
                        </a>

                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#"><i class="icon-user"></i> Perfil </a>
                            </li>
                            <li><a href="#"><i class="icon-gear"></i> Configuração </a>
                            </li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'sair', 'module' => 'login'));?>"><i class="icon-signout"></i> Sair </a>
                            </li>
                        </ul>

                    </li>
                    <!--END ADMIN SETTINGS -->
                </ul>

            </nav>

        </div>
        <!-- END HEADER SECTION -->



        <!-- MENU SECTION -->
       <div id="left" >
            <div class="media user-media well-small">
                <a class="user-link" href="#">
                    <img class="media-object img-thumbnail user-img" alt="User Picture" src="<?php echo $this->baseUrl('img/user.gif');?>" />
                </a>
                <br />
                <div class="media-body">
                    <h5 class="media-heading"> <?php echo $this->identidade->nome;?></h5>
                    <ul class="list-unstyled user-info">
                        
                        <li>
                             <a class="btn btn-success btn-xs btn-circle" style="width: 10px;height: 12px;"></a> Online
                           
                        </li>
                       
                    </ul>
                </div>
                <br />
            </div>

            <ul id="menu" class="collapse">
                <li class="panel active">
                    <a href="index.html" >
                        <i class="icon-table"></i> HOME
                    </a>                   
                </li>

            </ul>

        </div>
        <!--END MENU SECTION -->



        <!--PAGE CONTENT -->
        <div id="content">
             
            <div class="inner" style="min-height: 700px;">
                <div class="row">
                    <div class="col-lg-12">
                        <h1> LOGS </h1>
                    </div>
                </div>
                  <hr />
                  
                 <div>
                     <?php echo $this->layout()->content; ?>
                 </div>
                 
                 

                
            </div>

        </div>
        <!--END PAGE CONTENT -->
    </div>

    <!--END MAIN WRAPPER -->

    <!-- FOOTER -->
    <div id="footer">
        <p>&copy;  Painel Administrativo &nbsp;<?php echo date('Y');?> &nbsp;</p>
    </div>
    <!--END FOOTER -->


    <!-- GLOBAL SCRIPTS -->
    <script src="<?php echo $this->baseUrl('plugins/jquery-2.0.3.min.js');?>"></script>
     <script src="<?php echo $this->baseUrl('plugins/bootstrap/js/bootstrap.min.js');?>"></script>
    <script src="<?php echo $this->baseUrl('plugins/modernizr-2.6.2-respond-1.1.0.min.js');?>"></script>
    <!-- END GLOBAL SCRIPTS -->

    <!-- PAGE LEVEL SCRIPTS -->
    <script src="<?php echo $this->baseUrl('js/for_index.js');?>"></script>
   
    <!-- END PAGE LEVEL SCRIPTS -->


</body>

    <!-- END BODY -->
</html>
