<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="../../favicon.ico">

<title>PAINEL ADMINISTRATIVO</title>

<script src="<?php echo $this->baseUrl('js/jquery-1.11.2.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('js/jquery-migrate-1.2.1.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('js/plugins/validationengine/js/languages/jquery.validationEngine-pt_BR.js');?>"></script>
<script src="<?php echo $this->baseUrl('js/plugins/validationengine/js/jquery.validationEngine.js');?>"></script>
<script src="<?php echo $this->baseUrl('js/bootstrap.min.js');?>"></script>
<script src="<?php echo $this->baseUrl('js/bootstrap-checkbox.js');?>"></script>
<script src="<?php echo $this->baseUrl('js/scripts.js');?>"></script>

<!-- Bootstrap core CSS -->
<link href="<?php echo $this->baseUrl('css/bootstrap.min.css');?>" rel="stylesheet"/>
<link href="<?php echo $this->baseUrl('css/font-awesome.min.css');?>" rel="stylesheet"/>
<link href="<?php echo $this->baseUrl('css/estilo.css');?>" rel="stylesheet"/>
<link href="<?php echo $this->baseUrl('js/plugins/animate/animate.min.css');?>" rel="stylesheet"/>
<link href="<?php echo $this->baseUrl('css/bootstrap-checkbox.css');?>" rel="stylesheet"/>
<link rel="stylesheet" href="<?php echo $this->baseUrl('js/plugins/validationengine/css/validationEngine.jquery.css');?>" />

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

    <!-- END HEAD -->

    <!-- BEGIN BODY -->
    <body style="background: url('<?php echo $this->baseUrl('img/bgGeral.jpg');?>');">
          <!-- Static navbar -->
			<nav role="navigation" class="navbar navbar-default">
				<div class="container-fluid primary">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" class="navbar-toggle" type="button">
							<span class="sr-only">Navegação</span> <span class="icon-bar"></span>
							<span class="icon-bar"></span> <span class="icon-bar"></span>
						</button>
						<a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index', 'module' => 'default'));?>" class="navbar-brand"> 
							<img src="http://netsuprema.com.br/media/desenvolvido/net_124x42_preta.png" height="25" />
						</a>
					</div>
					<!-- Menu -->
					<div id="bs-example-navbar-collapse-1"
						class="collapse navbar-collapse">
						<ul class="nav navbar-nav">
						  
						  <?php 
						  
						  foreach ($this->grupo as $menu):
						  
						  ?>  
						  <li class="dropdown">
                              <a tabindex="0" data-toggle="dropdown">
                                 <i class="fa fa-users"></i>
                                  <?php echo $menu['nome']?> <span class="caret"></span>
                              </a>
                              <ul class="dropdown-menu" role="menu">
                                 <?php 
                                      $nome = 'modulo'.$menu['id'];
                                      $i=0;
                                      foreach ($this->$nome as $modulo):
                                      
                                      list($moduloNome, $controleNome) = explode(':',$modulo['nome']);
                                      
                                  ?>
                                  <li  class="dropdown-submenu">
                                     <a tabindex="<?php echo $i;?>" href="#" data-toggle="dropdown">
                                          <?php echo $modulo['nome_menu']?>
                                     </a>
                                      <?php 
                                          $nome = 'resource'.$modulo['id'];
                                          $i=0;
                                          $aDados = $this->$nome;
                                     if(isset($aDados[0]['id']) && $aDados[0]['id']):
                                     ?>
                                     <ul class="dropdown-menu">
                                          <?php 
                                              $nome = 'resource'.$modulo['id'];
                                              $i=0;
                                              foreach ($this->$nome as $resource):
                                          ?>
                                          <li>
                                              <a href="<?php echo $this->url(array('controller' => $controleNome, 'action' => $resource['resource'], 'module' => $moduloNome));?>">
                                                  <i class="fa fa-plus"></i>
                                                  <?php echo $resource['resource'];?>
                                              </a>
                                          </li>
                                          <?php
                                              $i++;
                                              endforeach;
                                          ?>
                                      </ul> 
                                      <?php endif;?>
                                  </li>
                                  <?php
                                      $i++;
                                      endforeach;
                                  ?>
                              </ul>
                          </li>
                          <?php endforeach;?>
						</ul>
						<ul class="nav navbar-nav navbar-right">
						  <li>
		                    <button type="button" class="btn navbar-btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="fa fa-wrench"></i> Configurações <span class="caret"></span></button>
		                    <ul class="dropdown-menu">
		                      <li><a href="/default/auth/sair">Sair</a></li>
		                    </ul>
		                  </li>
						</ul>
					</div>
					
				</div>
				
				<!-- /.container-fluid --> 
			</nav>
			<div>
				<!-- /.navbar-collapse -->
				<?php echo $this->layout()->content; ?>
			</div>
    </body>

    <!-- END BODY -->
</html>
