
<div class="container">
	<div class="row">
		<div class="col-md-6 col-xs-12 col-sm-6">
			<div class="panel panel-success" style="min-height: 190px;">
				<div class="panel-heading">
					<h3 class="panel-title">Painel de Manutenção de Conteúdo</h3>
				</div>
				<div class="panel-body">Bem vindo ao Sistema de Atualização e
					Manutenção de Conteúdo. Em caso de dificuldade entre em contato com
					contato@pixelgo.com.br</div>
			</div>
		</div>
		<div class="col-md-6 col-xs-12 col-sm-6">
			<div class="panel panel-success" style="min-height: 190px;">
				<div class="panel-heading">
					<h3 class="panel-title">Ultima Visita</h3>
				</div>
				<div class="panel-body">
					<div class="table-responsive" style="background: #fff;">
						<table class="table table-hover table-striped">
							<thead>
								<tr>
									<th>Id</th>
									<th>Nome</th>
									<th>Data</th>
									<th>Horário</th>
									<th>Ip</th>
								</tr>
							</thead>
							<tbody>
								<tr>
									<td>1</td>
									<td>Paulo Uere</td>
									<td>22/01/1987</td>
									<td>15:21</td>
									<td>192.168.7.10</td>
								</tr>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>


