<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

 <!-- BEGIN HEAD -->
<head>
    <meta charset="UTF-8" />
    <title>Erro!</title>
     <meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
     <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <!-- GLOBAL STYLES -->
  <!-- GLOBAL STYLES -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('plugins/bootstrap/css/bootstrap.css');?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('plugins/Font-Awesome/css/font-awesome.css');?>" />
    <!--END GLOBAL STYLES -->

     <!-- PAGE LEVEL STYLES -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/error.css');?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('lib/magic/magic.css');?>" />    
      <!--END PAGE LEVEL STYLES -->
   <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
     <!-- END HEAD -->
     <!-- BEGIN BODY -->
<body >
       <!--  PAGE CONTENT --> 
  <div class="container">
        <div class="col-lg-8 col-lg-offset-2 text-center">
	  <div class="logo">
	    <h3><?php echo $this->message ?></h3>
          </div>
          <p class="lead text-muted"> Ocorreu um erro!</p>
          <div class="clearfix"></div>
            <br />
            <div class="col-lg-6  col-lg-offset-3">
    		  <div class="btn-group btn-group-justified">
    		      <a href="javascript:history.go(-1);" class="btn btn-primary">Voltar</a>
    		  </div>
                    
            </div>
            
        </div>

                
        </div>
        
        <div style="padding-top: 10px;">
                
        <div class="container" style="padding: 10px 0px;">
	      <?php echo $this->exception->xdebug_message;?>
                    
        </div>
        <div class="container">
	      <?= var_dump($this->exception); ?>
                    
        </div>
        </div>

	      
	    <!-- END  PAGE CONTENT -->      


</body>
     <!-- END BODY -->
</html>

