<div>
	<div class="jumbotron">
		<div>
			<div class="table-responsive" style="padding: 30px;">
				<div class="container">
				    <a href="#" class="btn btn-block btn-md btn-primary modalDePesquisa" data-url="<?php echo $this->baseUrl();?>/default/usuario/pesquisar/type/json" data-toggle="tooltip" title="Filtra os resultados"><span class="glyphicon glyphicon-arrow-right"></span> FILTRAR RESULTADOS</a>
				</div>
				<table id="tblflat" class="table table-hover table-striped"
					width="100%" data-toggle="table" data-show-refresh="true"
					data-side-pagination="server"
					exportTypes="['json', 'xml', 'csv', 'txt', 'sql', 'excel', 'pdf']"
					data-url="<?php echo $this->baseUrl();?>/default/usuario/listar/type/json"
					data-show-export="true" data-show-columns="true"
					data-show-toggle="true" data-show-export="true"
					data-pagination="true">
					<thead>
						<tr>
							<th data-field="id" data-align="center" data-sortable="true">Id</th>
							<th data-field="grupo" data-align="center" data-sortable="true">Grupo</th>
							<th data-field="nome" data-align="center" data-sortable="true">Nome</th>
							<th data-field="email" data-align="center" data-sortable="true">Email</th>
							<th data-field="operate" data-formatter="operateFormatter" data-width="200" data-events="operateEvents">Ação</th>
						</tr>
					</thead>
				</table>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 col-xs-12 col-sm-12">
				<div align="center" style="padding-top: 10px;">
					<button type="button" class="btn btn-default cadastro-rapido">Cadastrar Novo
				    </button>
				</div>
			</div>
		</div>

	</div>
</div>

<link href="<?php echo $this->baseUrl($this->cssHelper);?>"
	media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript"
	src="<?php echo $this->baseUrl($this->jsHelper)?>"></script>



<div class="modal fade forget-modal-all" tabindex="-1" role="dialog" aria-labelledby="myForgetModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm">
		<div class="modal-content"></div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>
<!-- /.modal -->
