<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->

<!-- BEGIN HEAD -->
<head>
     <meta charset="UTF-8" />
    <title>PAINEL ADMINISTRATIVO</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
	<meta content="" name="description" />
	<meta content="" name="author" />
     <!--[if IE]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <![endif]-->
    <!-- GLOBAL STYLES -->
     <!-- PAGE LEVEL STYLES -->
    <link rel="stylesheet" href="<?php echo $this->baseUrl('plugins/bootstrap/css/bootstrap.css');?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('css/login.css');?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('plugins/magic/magic.css');?>" />
    <link rel="stylesheet" href="<?php echo $this->baseUrl('plugins/validationengine/css/validationEngine.jquery.css');?>" />
     <!-- END PAGE LEVEL STYLES -->
   <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
    <!-- END HEAD -->

    <!-- BEGIN BODY -->
<body >

   <!-- PAGE CONTENT --> 
    <div class="container">
    <div id="message_box">
        <?php echo $this->flashMessenger(); ?>
    </div>
    
    <?php echo $this->layout()->content; ?>


</div>

	  <!--END PAGE CONTENT -->     
	      
      <!-- PAGE LEVEL SCRIPTS -->
      <script src="<?php echo $this->baseUrl('plugins/jquery-2.0.3.min.js');?>"></script>
      <script src="<?php echo $this->baseUrl('plugins/bootstrap/js/bootstrap.js');?>"></script>
      <script src="<?php echo $this->baseUrl('js/login.js');?>"></script>
      <script src="<?php echo $this->baseUrl('plugins/validationengine/js/jquery.validationEngine.js');?>"></script>
      <script src="<?php echo $this->baseUrl('plugins/validationengine/js/languages/jquery.validationEngine-pt_BR.js');?>"></script>
      <script src="<?php echo $this->baseUrl('plugins/jquery-validation-1.11.1/dist/jquery.validate.min.js');?>"></script>
      <script src="<?php echo $this->baseUrl('js/validationInit.js');?>"></script>
      <!--END PAGE LEVEL SCRIPTS -->

</body>
    <!-- END BODY -->
</html>
