
<link href="<?php echo $this->baseUrl($this->cssHelper) ;?>"
	media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript"
	src="<?php echo $this->baseUrl($this->jsHelper)?>"></script>
	
	
<div class="modal-dialog modal-md">
	<div class="modal-content">
		<form action="javascript:;" id="frmPesquisar" data-url="<?php echo $this->baseUrl();?>/default/membro/get" class="form">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">
					<span aria-hidden="true">X</span>
					<span class="sr-only">Fechar</span>
				</button>
				<h4 class="modal-title">Filtrar Resultados</h4>
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Id</label>
				<input type="text" name="id" id="idPesquisar" class="form-control">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Módulo</label>
				<input type="text" name="modulo" id="moduloPesquisar" class="form-control">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Controle</label>
				<input type="text" name="ctrl" id="ctrlPesquisar" class="form-control">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Método</label>
				<input type="text" name="metodo" id="metodoPesquisar" class="form-control">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Ip</label>
				<input type="text" name="ip" id="ipPesquisar" class="form-control">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Data</label>
				<input type="text" name="data" id="dataPesquisar" class="form-control">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Id do Usuário</label>
				<input type="text" name="usuario_id" id="usuario_idPesquisar" class="form-control">
			</div>
			<div class="modal-body" style="padding: 3px 15px 0px 15px;">
				<label>Usuário Nome</label>
				<input type="text" name="usuario_nome" id="usuario_nomePesquisar" class="form-control">
			</div>
			<div class="modal-footer" style="margin-top: 5px;">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
				<button type="button" class="btn btn-default botaoPesquisar">Pesquisar</button>
			</div>
		</form>
	</div> <!-- /.modal-content -->
</div> <!-- /.modal-dialog -->
